// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZhq-l5vZ_lzkUhoSaMxGICdfLBPjLJDU',
    appId: '1:470131432213:ios:0a6ee5d9b05d47e40fa71c',
    messagingSenderId: '470131432213',
    projectId: 'control-activos-prestamos',
    storageBucket: 'control-activos-prestamos.firebasestorage.app',
    iosBundleId: 'com.example.proyectofinalmovil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZhq-l5vZ_lzkUhoSaMxGICdfLBPjLJDU',
    appId: '1:470131432213:ios:0a6ee5d9b05d47e40fa71c',
    messagingSenderId: '470131432213',
    projectId: 'control-activos-prestamos',
    storageBucket: 'control-activos-prestamos.firebasestorage.app',
    iosBundleId: 'com.example.proyectofinalmovil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDT3hbsN4KawKR7tIBteKeJfRqsvCOyl1U',
    appId: '1:470131432213:web:7dd919fc30c1006b0fa71c',
    messagingSenderId: '470131432213',
    projectId: 'control-activos-prestamos',
    authDomain: 'control-activos-prestamos.firebaseapp.com',
    storageBucket: 'control-activos-prestamos.firebasestorage.app',
    measurementId: 'G-BRB4PEP3J0',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT3hbsN4KawKR7tIBteKeJfRqsvCOyl1U',
    appId: '1:470131432213:web:7dd919fc30c1006b0fa71c',
    messagingSenderId: '470131432213',
    projectId: 'control-activos-prestamos',
    authDomain: 'control-activos-prestamos.firebaseapp.com',
    storageBucket: 'control-activos-prestamos.firebasestorage.app',
    measurementId: 'G-BRB4PEP3J0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwfplCEkcoVuKVmebZozJBZHqMy_vOsb4',
    appId: '1:470131432213:android:997c0e3b21338c0a0fa71c',
    messagingSenderId: '470131432213',
    projectId: 'control-activos-prestamos',
    storageBucket: 'control-activos-prestamos.firebasestorage.app',
  );

}